apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb  
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
